config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  resources (:users) do 
    resources :breaks, only: [:index]
  end 

  resources (:beaches) do 
    resources :breaks 
  end

  resources (:users) do 
    resources :profiles
  end 

  resources :breaks

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"

  get '/auth/facebook/callback', to: 'sessions#create_with_fb' 
  get '/auth/google_oauth2/callback', to: 'sessions#create_with_g' 


end

app/models/break.rb
class Break < ApplicationRecord
    belongs_to :user
    belongs_to :beach

    validates_presence_of :name, :location, :break_type, :direction, :height, :water_level, :suggested_skill_level, :shakas
    before_validation :title_case

    #scope(:breaks_search, ->(direction, shakas) {self.where(["direction = ?", direction], ["shakas = ?", shakas])}
    scope(:direction_search, ->(direction) {self.where("direction = ?", direction)})
    #scope(:name_search, ->(name) {self.where("name = ?", name)})

    def beach_name=(name)
        self.beach = Beach.find_or_create_by(name: name)
    end

    def beach_name
        self.beach ? self.beach.name : nil 
    end

    def title_case
        self.name = self.name.titlecase
    end


end

app/controllers/breaks_controller.rb
class BreaksController < ApplicationController
    before_action(:set_break, except: [:index, :new, :create])

    def index
        @user = User.find_by(id: params[:user_id])
            if @user 
                @breaks = @user.breaks
                    if params[:direction]
                        @all_breaks = Break.direction_search(params[:direction])
                    else
                        @all_breaks = Break.all
                    end
            else 
            redirect_to beaches_path
        end
    end
    
    def new
        if params[:beach_id]
            @beach = Beach.find_by(id: params[:beach_id])
            @breaks = @beach.breaks.build
        else 
            @break = Break.new
        end
    end

    def create 
        @break = Break.new(break_params)
        @break.user = current_user 
        if params[:beach_id]
            @break.beach_id = params[:beach_id]
        end
        if @break.save
            redirect_to breaks_path
        else
            render :new
        end
    end

    def edit
        break_owner
    end

    def update
        if @break.update(break_params)
            redirect_to (break_path(@break))
            flash[:message] = "Update Successful"
        else 
            render :edit
        end
    end

    def destroy
        break_owner
        @break.delete
        redirect_to user_breaks_path(current_user)
    end

    private

    def break_params
        params.require(:break).permit(:location, :name, :break_type, :direction, :height, :water_level, :suggested_skill_level, :shakas, :beach_name, :beach_id, :user_id)
    end

    def set_break
        @break = Break.find_by(id: params[:id])
    end

    

end

app/helpers/breaks_helper.rb
module BreaksHelper

    def form_url_helper(beach)
        beach ? beach_break_path(beach) : breaks_path
    end

end

app/views/breaks/_breaks.html.erb
        
    <% breaks.each do |b| %>
        <li> <%= link_to(b.name, user_breaks_path(b.user_id, b))%></li>
    <%end%>

app/views/breaks/_form.html.erb
<% if @break.beach %>
    <h2> Break at <%= @break.beach.name %></h2>
<%end%>
<h5> Add a new break </h5>
<%= form_for(@break, url: form_url_helper(@break.beach)) do |f| %>
    <%=f.label "Location" %>
    <%=f.text_field :location%><p><p>
    <%=f.label "Name" %>
    <%=f.text_field :name %><p>
    <%=f.label "Break Type" %>
    <%=f.text_field :break_type %><p>
    <%=f.label "Direction" %>
    <%=f.text_field :direction %><p>
    <%=f.label "Height" %>
    <%=f.text_field :height %><p>
    <%=f.label "Water Level" %>
    <%=f.text_field :water_level %><p>
    <%=f.label "Suggested Skill Level" %>
    <%=f.radio_button :suggested_skill_level, "Kooks Welcome" %> Kooks Welcome <%=f.radio_button :suggested_skill_level, "Easy" %> Easy <%=f.radio_button :suggested_skill_level, "Average" %> Average <%=f.radio_button :suggested_skill_level, "Experience Needed" %> Experience Needed <%=f.radio_button :suggested_skill_level, "Almost Pro" %> Almost Pro <p>
    <%=f.label "Shakas" %>
    <%=f.radio_button :shakas, 1 %> 1 <%=f.radio_button :shakas, 2 %> 2 <%=f.radio_button :shakas, 3 %> 3 <%=f.radio_button :shakas, 4 %> 4 <%=f.radio_button :shakas, 5 %> 5 <p>
    <%if !@break.beach%>
        <%=f.label :beach_name, "Beach"%>
        <%=f.text_field :beach_name, list: "beach_names"%>
        <datalist id="beach_names">
            <% all_beaches.each do |b| %>
            <option value="<%=b.name%>">
            <%end%>
            </datalist><p>
        <%end %><p>
    <%= f.submit "Submit" %>
<%end%>

app/views/breaks/edit.html.erb
<%= render(partial: "application/errors", locals: {errors: @break.errors.full_messages})%>

<%= render 'form' %> 

app/views/breaks/index.html.erb
   <h3><%=@user.username%>'s Breaks</h3>
   <% @breaks.each do |b| %>
      <li><%= link_to(b.name, beach_break_path(b.beach_id, b))%></li>
   <%end%><p>
   <%= link_to "Add new break?", new_break_path%>
<hr>
<h6> Search breaks by direction </h6>
   <%= form_with url: user_breaks_path(@user), method: :get do |f| %>
    <%= f.text_field :direction %>
    <%= f.submit "Search" %>
    <%end%>

<%= render(partial: "breaks", locals: {breaks: @all_breaks})%>

app/views/breaks/new.html.erb
<%= render(partial: "application/errors", locals: {errors: @break.errors.full_messages})%>

<% if @beach %>
    <h2> <%= @beach.name %></h2>
<%end%>

<%= form_for(@break, url: form_url_helper(@beach)) do |f| %>
    <%=f.label "Location" %>
    <%=f.text_field :location %><p>
    <%=f.label "Name" %>
    <%=f.text_field :name %><p>
    <%=f.label "Break Type" %>
    <%=f.text_field :break_type %><p>
    <%=f.label "Direction" %>
    <%=f.text_field :direction %><p>
    <%=f.label "Height" %>
    <%=f.text_field :height %><p>
    <%=f.label "Water Level" %>
    <%=f.text_field :water_level %><p>
    <%=f.label "Suggested Skill Level" %>
    <%=f.radio_button :suggested_skill_level, 1 %>Kooks Welcome<%=f.radio_button :suggested_skill_level, 2 %>Easy<%=f.radio_button :suggested_skill_level, 3 %>Average<%=f.radio_button :suggested_skill_level, 4 %>Experience Needed<%=f.radio_button :suggested_skill_level, 5 %>Almost Pro<p>
    <%=f.label "Shakas" %>
    <%=f.radio_button :shakas, 1 %>1<%=f.radio_button :shakas, 2 %>2<%=f.radio_button :shakas, 3 %>3<%=f.radio_button :shakas, 4 %>4<%=f.radio_button :shakas, 5 %>5<p>
    <%if !@beach%>
        <%=f.label :beach_id, "Beach"%>
        <%=f.text_field :beach_id, list: "beach_list"%>
        <datalist id="beach_list">
            <% @beaches.each do |n| %>
            <option value="<%= n.id%>"></option>
            <%end%>
            </datalist>
        <%end %>
    <%= f.submit "Submit" %>
<%end%>

app/views/breaks/show.html.erb
<h1><%= @break.name%></h1>
<p><label> Location: <%= @break.location%></label></p>
<p><label> Beach: <%=@break.beach_name %></label></p>
<p><label> Break: <%= @break.break_type%></label></p>
<p><label> Direction: <%= @break.direction%></label></p>
<p><label> Height: <%= @break.height%></label></p>
<p><label> Water Level: <%= @break.water_level%></label></p>
<p><label> Suggested Skill: <%= @break.suggested_skill_level%></label></p>
<p><label> Shakas: <%= @break.shakas%></label></p>
<% if @break.user_id == current_user.id %>
    <%= link_to "Edit", edit_break_path(@break) %><p>
    <%=button_to("Delete", @break, method: :delete, data: {confirm: "Are you sure?"}) %>
<%end%>