config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  resources (:users) do 
    resources :breaks, only: [:index]
  end 

  resources (:beaches) do 
    resources :breaks 
  end

  resources (:users) do 
    resources :profiles
  end 

  resources :breaks

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"

  get '/auth/facebook/callback', to: 'sessions#create_with_fb' 
  get '/auth/google_oauth2/callback', to: 'sessions#create_with_g' 


end

app/models/user.rb
class User < ApplicationRecord
    has_many :breaks
    has_many :beaches, through: :breaks
    has_one :profile

    has_secure_password
    validates_presence_of :username
    validates_uniqueness_of :username
    
    accepts_nested_attributes_for :breaks
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verified_user, only: [:new, :create]   
    before_action :set_user, except: [:new, :create] 

    def new
        @user = User.new
    end

    def create
      @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else @user
          render :new
        end
    end

    def update
      if @user.update(user_params)
          redirect_to user_path(@user)
          flash[:message] = "Update Successful"
      else
          render :edit
      end
  end


    def destroy
      @user.delete
      redirect_to root_path
    end


    private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def set_user
      @user = current_user
    end
    
end

app/helpers/users_helper.rb
module UsersHelper

    def form_user_helper(user)
        user ? user : signup_path(user)
    end

end

app/views/users/_form.html.erb
<h1> Please create an account</h1>

<%= render(partial: "application/errors", locals: {errors: @user.errors.full_messages})%>

<%= form_for @user, url: form_user_helper(@user) do |f| %>
    <%= f.label "Username" %>
    <%=f.text_field :username %><p><p>
    <%=f.label "Password" %>
    <%=f.password_field :password %><p>
    <%=f.label "Confirm Password" %>
    <%=f.password_field :password_confirmation %><p>
    <%=f.submit "Sign Up" %>
<%end%>


  <p>Sign up <%= link_to ' with Google', '/auth/google_oauth2'%>.</p>
  <div class="fb-login-button" data-width="" data-size="medium" data-button-type="login_with" data-layout="rounded" data-auto-logout-link="false" data-use-continue-as="true"></div>
  <p>Sign up <%= link_to ' with Facebook', '/auth/facebook'%>.</p>

app/views/users/edit.html.erb
<%= render(partial: "application/errors", locals: {errors: @user.errors.full_messages})%>

<h5> Update Password </h5>
<%= form_for @user do |f| %>
    <%=f.label "Password" %>
    <%=f.password_field :password %><p><p>
    <%=f.label "Confirm Password" %>
    <%=f.password_field :password_confirmation %><p>
    <%=f.submit "Update" %>
<%end%>

app/views/users/new.html.erb
<%= render 'form' %> 

app/views/users/show.html.erb
<h1> What up <%=current_user.username%>!</h1>

<%= link_to "Update Profile", new_user_profile_path(current_user) %><p><p>
<%= link_to "Edit Password", edit_user_path(current_user) %>
<%=button_to("Delete Account", @user, method: :delete, data: {confirm: "Are you sure?"}) %>