config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  resources (:users) do 
    resources :breaks, only: [:index]
  end 

  resources (:beaches) do 
    resources :breaks 
  end

  resources (:users) do 
    resources :profiles
  end 

  resources :breaks

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"

  get '/auth/facebook/callback', to: 'sessions#create_with_fb' 
  get '/auth/google_oauth2/callback', to: 'sessions#create_with_g' 


end

app/models/beach.rb
class Beach < ApplicationRecord
    has_many :breaks
    has_many :users, through: :breaks
    validates_presence_of :name
    validates_uniqueness_of :name
    before_validation :title_case

    accepts_nested_attributes_for :breaks

    scope(:beaches_search, -> (name) {self.where("lower(name) LIKE ?", "%#{name.downcase}%")})
#    scope(:users_search, -> (id) {self.where("id = ?", id)})
    scope(:beach_names, -> {self.order(:name)})


    def title_case
        self.name = self.name.titlecase
    end

end

app/controllers/beaches_controller.rb
class BeachesController < ApplicationController 
    before_action :set_beach, except: [:index, :new, :create]
    
    def index
        if params[:name]
            @beaches = Beach.beaches_search(params[:name])
        else
            @beaches = Beach.beach_names
        end
    end

    def show
    end
    
    def new
        @beach = Beach.new
        @beach.breaks.build(user: current_user)
        @breaks = @beach.breaks.select{|b| b.user_id == current_user.id}  
    end

    def create 
        @beach = Beach.new(beach_params)
        @beach.breaks.each {|b| b.user = current_user}
        if @beach.save
            redirect_to user_beach_path(current_user, @beach)
        else
            render :new
        end
    end

    def edit
        @beach = Beach.find_by(id: params[:id])
    end

    def update
        if @beach.update(beach_params)
            redirect_to(beach_path(@beach))
            flash[:message] = "Update Successful"
        else
            @breaks = @beach.breaks.select{|b| b.user_id == current_user.id}  
            render :edit
        end
    end


    #Coding exercises not related to the project 
    # def most
    #     @beach = Beach.all.max {|a, b| a.breaks.count <=> b.breaks.count }
    # end 

    # def beaches_users
    #     if params[:beach_id]
    #         @beach = Beach.users_search(params[:beach_id]).first
    #         @users = @beach.users
    #     end
    # end

    private 

    def beach_params
        params.require(:beach).permit(:name, :street, :parking, :city, breaks_attributes: [:name, :user_id, :id, :beach_name, :location, :beach_id, :break_type, :direction, :height, :water_level, :suggested_skill_level, :shakas])
    end

    def set_beach
        @beach = Beach.find_by(id: params[:id])
    end

end

app/helpers/beaches_helper.rb
module BeachesHelper

    def my_beaches
        @my_beaches = current_user.beaches.uniq
    end

    def all_beaches
        Beach.all
    end

    def beach_break
        @breaks = @beach.breaks.where(user_id: current_user.id)
    end

end

app/views/beaches/_form.html.erb
<h4> Add a beach </h4>
<%= form_for @beach do |f| %>
    <%=f.label "Beach Name:" %>
    <%=f.text_field :name %><p><p>
    <%=f.label "Street Address" %>
    <%=f.text_field :street %><p>
    <%=f.label "City" %>
    <%=f.text_field :city %><p>
    <%=f.label "Parking" %>
    <%=f.text_field :parking %><p>
    <h5> Add a Surf Break </h5>
    <%=f.fields_for :breaks, @breaks do |b| %>
        <%=b.label "Name" %>
        <%=b.text_field :name %><p><p>
        <%=b.label "Location" %>
        <%=b.text_field :location %><p>
        <%=b.label "Break Type" %>
        <%=b.text_field :break_type %><p>
        <%=b.label "Direction" %>
        <%=b.text_field :direction %><p>
        <%=b.label "Height" %>
        <%=b.text_field :height %><p>
        <%=b.label "Water Level" %>
        <%=b.text_field :water_level %><p>
        <%=b.label "Suggested Skill Level" %>
        <%=b.radio_button :suggested_skill_level, "Kooks Welcome" %> Kooks Welcome <%=b.radio_button :suggested_skill_level, "Easy" %> Easy <%=b.radio_button :suggested_skill_level, "Average" %> Average <%=b.radio_button :suggested_skill_level, "Experience Needed" %> Experience Needed <%=b.radio_button :suggested_skill_level, "Almost Pro" %> Almost Pro <p>
        <%=b.label "Shakas" %>
        <%=b.radio_button :shakas, 1 %> 1 <%=b.radio_button :shakas, 2 %> 2 <%=b.radio_button :shakas, 3 %> 3 <%=b.radio_button :shakas, 4 %> 4 <%=b.radio_button :shakas, 5 %> 5 <p>
        <%end%>
    <%=f.submit "Submit" %>
<%end%>

app/views/beaches/edit.html.erb
<%= render(partial: "application/errors", locals: {errors: @beach.errors.full_messages})%>

<%= render('form')%> 

app/views/beaches/index.html.erb
  <h3>Favorite Beaches</h3>
   <ul><% my_beaches.each do |b| %></ul>
      <li><%= link_to(b.name, beach_path(b))%></li>
   <%end%>
   <%= link_to "Add new beach?", new_beach_path%>
   
   <hr>

   <h6> Search for a beach </h6>
   <%= form_with url: beaches_path, method: :get do |f| %>
    <%= f.text_field :name%>
    <%= f.submit "Search" %>
   <%end%>


   <% @beaches.each do |b| %>
   <li><%= link_to(b.name, beach_path(b))%></li>
<%end%>

app/views/beaches/new.html.erb
<%= render(partial: "application/errors", locals: {errors: @beach.errors.full_messages})%>

<%= render 'form' %> 

app/views/beaches/show.html.erb
<h1> Beach Show Page </h1>

<h3><%=@beach.name %></h3>
<%= @beach.street %><p><p>
<%= @beach.city %><p>
<%= @beach.parking %><p>
<%= render(partial: "breaks/breaks", locals: {breaks: @beach.breaks}) %><p><p>
<%= link_to "Add new break?", new_break_path%><p>
<% if !@beach.street%>
    <%= link_to "Edit Beach", edit_beach_path(@beach)%>
<%end%>