config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  resources (:users) do 
    resources :breaks, only: [:index]
  end 

  resources (:beaches) do 
    resources :breaks 
  end

  resources (:users) do 
    resources :profiles
  end 

  resources :breaks

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"

  get '/auth/facebook/callback', to: 'sessions#create_with_fb' 
  get '/auth/google_oauth2/callback', to: 'sessions#create_with_g' 


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<title>Surf Buddies</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "helvicta", sans-serif}
</style>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>

  <!-- Navbar -->
  <head>
  <div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="<%= root_path %>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">HOME</a>
      <% if !current_user %>
        <a href="<%= new_user_path %>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Sign Up</a>
        <a href="<%= login_path %>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Log In</a>  
      <% end %>
      <% if current_user %>
          <a href="<%= beaches_path%>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Beaches</a>
          <a href="<%= user_breaks_path(current_user)%>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Breaks</a>
          <a href="<%= new_user_profile_path(current_user)%>" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Profile</a>
          <%= link_to "LOG OUT",  logout_path, class:"w3-padding-large w3-button w3-hover-red w3-hide-small w3-right", method: :post %>
    <% end %>
  </div>
</div>
</head>

<!-- Header -->
<header>
<body>
<div class="w3-content" style="max-width:3000px;margin-top:65px;margin-left:5px;">
  <%=flash[:message]%>  
  <%= yield %>
  </body>
  </header>

<!-- Footer -->
<footer class="w3-container w3-black" style="max-width:fit;margin-top:50px">
  <small>&copy; 2021 <strong>Surf Buddies</strong></small>
</footer>

</html>